name: Build Docker

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up for QEMU
        uses: docker/setup-qemu-action@v1
      - name: Loginto Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{  secrets.PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{  env.working.directory }}
          tags: |
            ghcr.io/mikael95/mikael95/simpleazurecosmosdbwebapp:V3
