# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - songdatabase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://myeducationalregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e3bd759971a34352ad53cc72cbf1a3c5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7360a42c5f8f42a3881029b9ce80c123 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: myeducationalregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e3bd759971a34352ad53cc72cbf1a3c5 }}/mikael95/simpleazurecosmosdbwebapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'songdatabase'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_94b02b6391d04f1c88dc47d8d32f7c14 }}
        images: 'myeducationalregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e3bd759971a34352ad53cc72cbf1a3c5 }}/mikael95/simpleazurecosmosdbwebapp:${{ github.sha }}'