# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - songCosmosDb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/mikael95/
        username: ${{ secrets.AzureAppService_ContainerUsername_08830f24fd344a9a955041a5effd0662 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_df312e076dc84378b1c5ecbf4db5714f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/mikael95/${{ secrets.AzureAppService_ContainerUsername_08830f24fd344a9a955041a5effd0662 }}/mikael95/simpleazurecosmosdbwebapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'songCosmosDb'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6d05b64236cb4aed84ced26038010d33 }}
        images: 'ghcr.io/mikael95/${{ secrets.AzureAppService_ContainerUsername_08830f24fd344a9a955041a5effd0662 }}/mikael95/simpleazurecosmosdbwebapp:${{ github.sha }}'